-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. Flights Table
create table public.flights (
  id uuid primary key default uuid_generate_v4(),
  flight_number text not null,
  origin text not null,
  destination text not null,
  departure_time timestamptz not null,
  arrival_time timestamptz not null,
  price numeric not null,
  status text default 'On Time',
  created_at timestamptz default now()
);

-- Enable RLS for flights
alter table public.flights enable row level security;

-- Policies for flights
create policy "Flights are viewable by everyone" 
  on public.flights for select 
  using (true);

create policy "Authenticated users can insert flights (Admin)" 
  on public.flights for insert 
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update flights (Admin)" 
  on public.flights for update 
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete flights (Admin)" 
  on public.flights for delete 
  using (auth.role() = 'authenticated');


-- 2. Passengers Table (Stores Booking Details)
create table public.passengers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  flight_id uuid references public.flights(id) on delete cascade not null,
  seat_number text not null,
  passenger_name text not null,
  passenger_age int not null,
  passenger_gender text not null,
  booking_id text, -- Shared ID for grouped passengers or payment reference
  payment_status text default 'pending',
  created_at timestamptz default now()
);

-- Enable RLS for passengers
alter table public.passengers enable row level security;

-- Policies for passengers
create policy "Users can view their own bookings" 
  on public.passengers for select 
  using (auth.uid() = user_id);

create policy "Users can insert their own bookings" 
  on public.passengers for insert 
  with check (auth.uid() = user_id);

create policy "Admins can view all bookings" 
  on public.passengers for select 
  using (true); -- You might want to restrict this to actual admins later

create policy "Admins/Users can delete bookings" 
  on public.passengers for delete 
  using (auth.uid() = user_id); -- Or true for admins


-- 3. Payments Table
create table public.payments (
  id uuid primary key default uuid_generate_v4(),
  booking_id text,
  razorpay_payment_id text,
  amount numeric,
  status text,
  payment_status text,
  created_at timestamptz default now()
);

-- Enable RLS for payments
alter table public.payments enable row level security;

create policy "Users can insert payments" 
  on public.payments for insert 
  with check (true);

create policy "Users can view payments" 
  on public.payments for select 
  using (true);
